Models/ErrorViewModel.cs
namespace trabajo.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Libro.cs
namespace trabajo.Models;

public class Libro
{
    public int Id { get; set; }
    public string Titulo {get; set;}
    public string Autor { get; set; }
    public string Codigo { get; set; }
    public int EjemplaresDisponibles { get; set; }
}

Models/Prestamo.cs
namespace trabajo.Models;

public class Prestamo
{
    public int Id { get; set; }
    public int UserId { get; set; }
    public User Usuario { get; set; }
    public int LibroId { get; set; }
    public Libro Libro { get; set; }
    public DateTime FechaPrestamo { get; set; } = DateTime.Now;
    public DateTime FechaDevolucion { get; set; }
    public bool Devuelto { get; set; } = false;
}  

Models/User.cs
namespace trabajo.Models;

public class User
{
    public int Id { get; set; }
    public string Nombre { get; set; }
    public string Documento { get; set; }
    public string Correo { get; set; }
    public string Telefono {get; set;}
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using trabajo.Models;

namespace trabajo.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/LibrosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using trabajo.Data;
using trabajo.Models;

namespace trabajo.Controllers;

public class LibrosController: Controller
{
    private readonly AppDbContext _appDbContext;

    public LibrosController(AppDbContext appDbContext)
    {
        _appDbContext = appDbContext;
    }

    public async Task<IActionResult> Index()
    {
        List<Libro> lista = await _appDbContext.Libros.ToListAsync();
        return View(lista);
    }

    public IActionResult Agregar()
    {
        return View();
    }

    public async Task<IActionResult> Nuevo(Libro libro)
    {
        await _appDbContext.Libros.AddAsync(libro);
        await _appDbContext.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }
}

Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using trabajo.Data;
using trabajo.Models;

namespace trabajo.Controllers;

public class UsuariosController : Controller
{
    private readonly AppDbContext _appDbContext;

    public UsuariosController(AppDbContext appContext)
    {
        _appDbContext = appContext;
    }
    public async Task<IActionResult> Index()
    {
        List<User> lista = await _appDbContext.Users.ToListAsync();
        return View(lista);
    }
    
    public IActionResult Agregar()
    {
        return View();
    }
    
    public async Task<IActionResult> nuevo(User user)
    {
        await _appDbContext.Users.AddAsync(user);
        await _appDbContext.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }
    
    public async Task<IActionResult> Editar(int Id)
    {
        User user = await _appDbContext.Users.FirstOrDefaultAsync(u => u.Id == Id);
        return View(user);
    }
    
    public async Task<IActionResult> Editar(User user)
    { 
        _appDbContext.Users.Update(user);
        await _appDbContext.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Libros/Index.cshtml
@model IEnumerable<trabajo.Models.Libro>
<h1>lista libros</h1>
<div class="row">
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Titulo</th>
            <th>Autor</th>
            <th>Codigo</th>
            <th>Ejemplares disponibles</th>
            <a asp-controller="Libros" asp-action="Agregar" class="btn btn-success mb-3" >agregar</a>
            @* <th> *@
            @*     <button class="btn btn-warning" type="button"data-bs-toggle="modal" data-bs-target="#addProductModal"> Add</button> *@
            @* </th> *@
        </tr>
        </thead>
        <tbody>
        @foreach (var lib in Model)
        {
            <tr>
                <td>@lib.Id</td>
                <td>@lib.Titulo</td>
                <td>@lib.Autor</td>
                <td>@lib.Codigo</td>
                <td>@lib.EjemplaresDisponibles</td>
            </tr>
        }
        </tbody>
    </table>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - trabajo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/trabajo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">trabajo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - trabajo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Usuarios/Agregar.cshtml
@model trabajo.Models.User

<div class="row">
    <h2>agregar usuarios</h2>
    <form asp-controller="Usuarios" asp-action="nuevo">
        <div class="mb-3">
            <lable>Nombre</lable>
            <input class="form-control" asp-for="Nombre" type="text">
        </div>
        <div class="mb-3">
            <lable>Documento</lable>
            <input class="form-control" asp-for="Documento" type="text">
        </div>
        <div class="mb-3">
            <lable>Correo</lable>
            <input class="form-control" asp-for="Correo" type="text">
        </div>
        <div class="mb-3">
            <lable>Telefono</lable>
            <input class="form-control" asp-for="Telefono" type="text">
        </div>
        <div class="mb-3">
            <button class="btn btn-primary" type="submit">agregar</button>
            <a asp-controller="Usuarios" asp-action="Index" class="btn btn-warning">volver</a>
        </div>
    </form>
</div>

Views/Usuarios/Index.cshtml
@model IEnumerable<trabajo.Models.User>
<h1>lista usuarios</h1>
<div class="row">
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Documento</th>
            <th>Correo</th>
            <th>Telefono</th>
            <a asp-controller="Usuarios" asp-action="Agregar" class="btn btn-success mb-3" >agregar</a>
            @* <th> *@
            @*     <button class="btn btn-warning" type="button"data-bs-toggle="modal" data-bs-target="#addProductModal"> Add</button> *@
            @* </th> *@
        </tr>
        </thead>
        <tbody>
        @foreach (var use in Model)
        {
            <tr>
                <td>@use.Id</td>
                <td>@use.Nombre</td>
                <td>@use.Documento</td>
                <td>@use.Correo</td>
                <td>@use.Telefono</td>
            </tr>
        }
        </tbody>
    </table>
</div>